name:       cs340mp4

# By signing below, I pledge on my honor that I neither gave nor received any
# unauthorized assistance on the code contained in this repository.

author:     "Jane Downer"      # your name
maintainer: "jdowner@hawk.iit.edu"  # your IIT email

dependencies:
- base >= 4.7 && < 5
- gloss
- hspec
- HUnit
- HUnit-approx
- QuickCheck

executables:
  mp3:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cs340mp4

library:
  source-dirs: src

tests:
  mp3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cs340mp4
