name:       cs340midterm

dependencies:
- base >= 4.7 && < 5
- hspec
- HUnit
- HUnit-approx
- QuickCheck

library:
  source-dirs: src

tests:
  midterm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cs340midterm
